server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_project_dawi_final
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: TuClaveSuperSecretaMuyLarga1234567890
  expiration: 36000000
